// search.js
export const SEARCH_FOR_MOVIE = 'SEARCH_FOR_MOVIE';
export const SEARCH_FOR_MOVIE_SUCCESS = 'SEARCH_FOR_MOVIE_SUCCESS';
export const SEARCH_FOR_MOVIE_FAILURE = 'SEARCH_FOR_MOVIE_FAILURE';
