name: Sofatorrent - Continuous Integration | Master

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: BACKEND - npm install, build, and test
        run: |
          cd backend/
          npm ci
          npm test
        env:
          CI: true
      - name: FRONTEND - npm install, build, and test
        run: |
          cd frontend/
          npm ci
          ENV=production npm run build --if-present
          npm test
        env:
          CI: true
